# Version of the baseline commit. Conventional commits after this point are
# applied in chronological order to calculate the current language version.
VERSION_BASE=0.1.14
VERSION_BASE_COMMIT=4e5a8b1
