# Version of the baseline commit. Conventional commits after this point are
# applied in chronological order to calculate the current language version.
VERSION_BASE=0.68.1
VERSION_BASE_COMMIT=e45ad16
