#!/usr/bin/env bash
set -euo pipefail

export PATH="/c/msys64/ucrt64/bin:/ucrt64/bin:/usr/bin:/bin:$PATH"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"
binary="./bin/sagan"
mkdir -p build
work_dir="$(mktemp -d build/cli-test.XXXXXXXXXX)"

cleanup() {
  rm -rf "$work_dir"
}
trap cleanup EXIT

expect_output() {
  local name="$1"
  local expected="$2"
  shift 2
  local output
  output="$("$@" 2>&1)" || {
    echo "[FAIL] $name: command failed" >&2
    echo "$output" >&2
    return 1
  }
  grep -Fq "$expected" <<<"$output" || {
    echo "[FAIL] $name: expected output containing '$expected'" >&2
    echo "$output" >&2
    return 1
  }
  echo "[PASS] $name"
}

expect_failure() {
  local name="$1"
  local expected_status="$2"
  local expected="$3"
  shift 3
  local output
  local status
  set +e
  output="$("$@" 2>&1)"
  status=$?
  set -e
  if [[ "$status" -ne "$expected_status" ]]; then
    echo "[FAIL] $name: expected status $expected_status, got $status" >&2
    echo "$output" >&2
    return 1
  fi
  grep -Fq "$expected" <<<"$output" || {
    echo "[FAIL] $name: expected output containing '$expected'" >&2
    echo "$output" >&2
    return 1
  }
  echo "[PASS] $name"
}

expect_output "default tokenizer input" "tokenizer: examples/tokenizer_demo.sagan" "$binary"
expect_output "version output" "Sagan " "$binary" --version
expect_output "explicit tokenizer input" "KWD_LET" "$binary" examples/tokenizer_demo.sagan
printf '%s\n' 'let escaped = "\r\t\0"' > "$work_dir/escaped.sagan"
expect_output "escaped token text" '\r\t\0' "$binary" "$work_dir/escaped.sagan"
expect_output "text AST output" "Program" "$binary" --ast examples/parser_demo.sagan
expect_output "DOT AST output" "digraph SaganAST" "$binary" --ast-dot examples/parser_demo.sagan
expect_output "semantic model output" "SemanticModel" \
  "$binary" --semantic examples/semantic_demo.sagan
expect_output "type model output" "TypeModel" \
  "$binary" --types examples/type_demo.sagan
expect_output "entry-point validation" "executable entry point is valid" \
  "$binary" --entry examples/entry_demo.sagan
expect_output "module graph resolution" "Import(course from guidance as calculate_course)" \
  "$binary" --modules examples/module_demo/main.sagan
expect_output "linked module C++ output" "Cross-module answer" \
  "$binary" --emit-cpp-modules examples/module_demo/main.sagan
expect_output "C++ output" "Generated by Sagan" \
  "$binary" --emit-cpp examples/execution_demo.sagan
expect_output "C++ output file" "Wrote generated C++" \
  "$binary" --emit-cpp examples/execution_demo.sagan "$work_dir/generated.cpp"
grep -Fq "int main()" "$work_dir/generated.cpp"
grep -Fq "enum class sagan_4c61756e6368537461747573" "$work_dir/generated.cpp"
grep -Fq "sagan_4c61756e6368537461747573::sagan_7265616479" "$work_dir/generated.cpp"
grep -Fq "private:" "$work_dir/generated.cpp"
grep -Fq "sagan_726561645f76616c7565" "$work_dir/generated.cpp"
grep -Fq "sagan_6e657874()" "$work_dir/generated.cpp"
grep -Fq "SetConsoleOutputCP(CP_UTF8)" "$work_dir/generated.cpp"
grep -Fq "std::vector<std::int8_t>" "$work_dir/generated.cpp"
grep -Fq "for (auto" "$work_dir/generated.cpp"
grep -Fq ".at(2)" "$work_dir/generated.cpp"
grep -Fq "sagan_stringify" "$work_dir/generated.cpp"
grep -Fq "while (" "$work_dir/generated.cpp"
grep -Fq "sagan_subtract_assign<std::int8_t>" "$work_dir/generated.cpp"
grep -Fq "std::unordered_map<std::string, std::int8_t>" "$work_dir/generated.cpp"
grep -Fq "sagan_array_0.insert" "$work_dir/generated.cpp"
grep -Fq "sagan_spread_0_0" "$work_dir/generated.cpp"
grep -Fq "sagan_spread_0_2" "$work_dir/generated.cpp"
grep -Fq "sagan_dictionary_1.insert_or_assign" "$work_dir/generated.cpp"
grep -Fq "sagan_dictionary_spread_1_0" "$work_dir/generated.cpp"
grep -Fq "sagan_increment<std::int8_t>(sagan_6c61756e63685f6e756d626572, true)" "$work_dir/generated.cpp"
grep -Fq "sagan_increment<std::int8_t>(sagan_6c61756e63685f6e756d626572, false)" "$work_dir/generated.cpp"
grep -Fq "sagan_power<std::int8_t>(3, 2)" "$work_dir/generated.cpp"
grep -Fq "sagan_power<double>(2.0, static_cast<std::int8_t>(-1))" "$work_dir/generated.cpp"
grep -Fq "sagan_power_assign<std::int8_t>" "$work_dir/generated.cpp"
grep -Fq "sagan_add_assign<std::int8_t>" "$work_dir/generated.cpp"
grep -Fq "sagan_multiply_assign<std::int8_t>" "$work_dir/generated.cpp"
grep -Fq "sagan_divide_assign<std::int8_t>" "$work_dir/generated.cpp"
grep -Fq "sagan_modulo_assign<std::int8_t>" "$work_dir/generated.cpp"
grep -Fq "sagan_subtract_assign<std::int8_t>" "$work_dir/generated.cpp"
grep -Fq "sagan_multiply<std::int8_t>(6, 7)" "$work_dir/generated.cpp"
grep -Fq "sagan_modulo<double>(5.5, 2.0)" "$work_dir/generated.cpp"
grep -Fq "sagan_vector<double, 3>" "$work_dir/generated.cpp"
grep -Fq "sagan_coordinate<double, 3>" "$work_dir/generated.cpp"
grep -Fq "sagan_dimensioned_spread_0_0" "$work_dir/generated.cpp"
grep -Fq "sagan_add<sagan_vector<double, 3>>" "$work_dir/generated.cpp"
grep -Fq "sagan_multiply<sagan_vector<double, 3>>(2.0" "$work_dir/generated.cpp"
grep -Fq "sagan_negate<sagan_vector<double, 3>>" "$work_dir/generated.cpp"
grep -Fq "[&](std::int64_t" "$work_dir/generated.cpp"
grep -Fq "sagan_6c61756e63685f7472616e73666f726d(40)" "$work_dir/generated.cpp"
grep -Fq "struct sagan_4c61756e6368436f756e746572" "$work_dir/generated.cpp"
grep -Fq "(*this).sagan_76616c7565" "$work_dir/generated.cpp"
grep -Fq "sagan_696e6372656d656e7421()" "$work_dir/generated.cpp"
grep -Fq ".at(2)" "$work_dir/generated.cpp"
grep -Fq ".at(1)" "$work_dir/generated.cpp"
grep -Fq "const auto sagan_match_" "$work_dir/generated.cpp"
grep -Fq "else {" "$work_dir/generated.cpp"
grep -Fq "sagan_scream<std::string>" "$work_dir/generated.cpp"
grep -Fq "sagan_exception_matches<std::string>" "$work_dir/generated.cpp"
grep -Fq "sagan_make_finally" "$work_dir/generated.cpp"

expect_output "SVG AST file" "Wrote SVG AST" \
  "$binary" --ast-svg examples/parser_demo.sagan "$work_dir/parser.svg"
grep -Fq "<svg" "$work_dir/parser.svg"

expect_output "HTML AST file" "Wrote visual AST demo" \
  "$binary" --ast-html examples/parser_demo.sagan "$work_dir/parser.html"
grep -Fq "Input source" "$work_dir/parser.html"

expect_failure "invalid arguments" 2 "usage: sagan" "$binary" --ast one.sagan extra.sagan
expect_failure "missing input file" 1 "Could not open" "$binary" "$work_dir/missing.sagan"
expect_failure "lexical diagnostic" 1 "lexical error at" "$binary" examples/tokenizer_error.sagan
expect_failure "syntax diagnostic" 1 "syntax error at" "$binary" --ast examples/parser_error.sagan
expect_failure "undefined-name semantic diagnostic" 1 "Undefined name 'missing_value'" \
  "$binary" --semantic examples/semantic_undefined_error.sagan
expect_failure "duplicate-name semantic diagnostic" 1 "Duplicate declaration of 'repeated'" \
  "$binary" --semantic examples/semantic_duplicate_error.sagan
expect_failure "type diagnostic" 1 "Function return requires Bool, but received Int" \
  "$binary" --types examples/type_error.sagan
expect_failure "uninferred variable diagnostic" 1 "requires a type annotation or initializer" \
  "$binary" --types examples/type_uninferred_error.sagan
expect_failure "heterogeneous array diagnostic" 1 "Array elements have incompatible types" \
  "$binary" --types examples/type_array_error.sagan
expect_failure "heterogeneous dictionary diagnostic" 1 "Dictionary values have incompatible types" \
  "$binary" --types examples/type_dictionary_error.sagan
expect_failure "vector component diagnostic" 1 "Vector components must be numeric" \
  "$binary" --types examples/type_vector_error.sagan
expect_failure "annotation type diagnostic" 1 "does not name a type" \
  "$binary" --types examples/type_annotation_error.sagan
expect_failure "definite return diagnostic" 1 "may reach the end without returning Int64" \
  "$binary" --types examples/type_return_error.sagan
expect_failure "missing entry-point diagnostic" 1 "requires a 'main' entry point" \
  "$binary" --entry examples/entry_missing_error.sagan
expect_failure "uninitialized variable diagnostic" 1 "is used before initialization" \
  "$binary" --types examples/type_uninitialized_error.sagan
expect_failure "unreachable statement diagnostic" 1 "Unreachable statement" \
  "$binary" --types examples/type_unreachable_error.sagan
expect_failure "module cycle diagnostic" 1 "Cyclic module dependency: alpha -> beta -> alpha" \
  "$binary" --modules examples/module_cycle/alpha.sagan
expect_failure "missing module export diagnostic" 1 "does not export 'missing'" \
  "$binary" --modules examples/module_export_error/main.sagan
expect_failure "module name diagnostic" 1 "declares 'wrong_name', expected 'main'" \
  "$binary" --modules examples/module_name_error/main.sagan
expect_failure "missing module file diagnostic" 1 "Could not open module" \
  "$binary" --modules examples/module_missing/main.sagan
expect_failure "missing module declaration diagnostic" 1 "must declare 'module support'" \
  "$binary" --modules examples/module_declaration_error/main.sagan
expect_failure "undefined module export diagnostic" 1 "exports undefined declaration 'missing'" \
  "$binary" --modules examples/module_undefined_export_error/main.sagan
expect_failure "duplicate module export diagnostic" 1 "exports duplicate public name 'value'" \
  "$binary" --modules examples/module_duplicate_export_error/main.sagan
expect_failure "module extension diagnostic" 1 "must use the .sagan extension" \
  "$binary" --modules README.md
expect_failure "linked module type diagnostic" 1 "No matching overload for 'guidance__calculate'" \
  "$binary" --emit-cpp-modules examples/module_type_error/main.sagan
expect_failure "module namespace visibility diagnostic" 1 "Module 'support' does not export 'private_value'" \
  "$binary" --emit-cpp-modules examples/module_namespace_error/main.sagan
expect_failure "unwritable output" 1 "Could not write" \
  "$binary" --ast-svg examples/parser_demo.sagan "$work_dir/missing/output.svg"

echo "All command-line integration tests passed."
